#!/bin/bash
# This script submitts all jobs to naf, which are defined in dataset

datasets=(
# srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/nTuples/QCD_250-500_V01/
# srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/nTuples/QCD_500-1000_V01/
# srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/nTuples/QCD_1000-inf_V01/
# srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/nTuples/GJets_V01/
# srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/nTuples/WJets_V01/
# srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/nTuples/TTJets_V01/
# srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/nTuples/DY_to_ee/
# srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/nTuples/GVJets_V01/
#srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/QCD_HT-250To500_TuneZ2star_8TeV-madgraph-pythia6/susyMC_QCD_250-500_V02/f278a418b8539fca8b5777b718a2a1aa/
#srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/QCD_HT-500To1000_TuneZ2star_8TeV-madgraph-pythia6/susyMC_QCD_500-1000_V02/f278a418b8539fca8b5777b718a2a1aa/
#srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/QCD_HT-1000ToInf_TuneZ2star_8TeV-madgraph-pythia6/susyMC_QCD_1000-inf_V02/f278a418b8539fca8b5777b718a2a1aa/
#srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/GJets_HT-400ToInf_8TeV-madgraph_v2/susyMC_GJets_V02/f278a418b8539fca8b5777b718a2a1aa/
#srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/WGToLNuG_TuneZ2star_8TeV-madgraph-tauola/susyMC_WGamma_V02/f278a418b8539fca8b5777b718a2a1aa/
#srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball/susyMC_WJets_V02/f278a418b8539fca8b5777b718a2a1aa/
#srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/GVJets_Incl_8TeV-madgraph/susyMC_GVJets_V02/f278a418b8539fca8b5777b718a2a1aa/
#srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/jschulz/ZG_Inclusive_8TeV-madgraph_v2/susyMC_ZGamma_V02/f278a418b8539fca8b5777b718a2a1aa/
)
# settings
version="14"
outputFolder=/scratch/hh/dust/naf/cms/user/kiesel
files_per_job=20

fetchScript=getOutput_${version}.sh
echo "#!/bin/bash -e" > $fetchScript
chmod +x $fetchScript

for dataset in "${datasets[@]}"; do

    # get folder name as best description for job
    job_name=$(echo $dataset|rev|cut -d'/' -f2|rev)
    # Since root can't handle -, it will be substituted to _
    job_name=$(echo $job_name|sed 's/-/_/g')

    files=( $(srmls -offset 0 -count 999 $dataset|grep root|awk '{print $2 }') )
    # Ugly hack to get more than 1000 files (up to 2000).
    files+=( $(srmls -offset 1000 -count 1999 $dataset|grep root|awk '{print $2 }') )
    number_of_jobs=$(expr ${#files[@]} / $files_per_job + 1 )

    # just for testing purpurse
    #TMPDIR=/tmp


    for (( job=1; job<=$number_of_jobs; job++ )); do

        jobPrefix=${job_name}.${version}__${job}

        files_to_submit=""
        for (( i=$(expr $job \* $files_per_job - $files_per_job  ); i<$(expr $job \* $files_per_job ); i++ )); do
            if [[ "${files[$i]}" != "" ]]; then
                files_to_submit=$files_to_submit"dcap://dcache-cms-dcap.desy.de"${files[$i]}" "
            fi
        done # files for one job
        outputFileName=$outputFolder/${jobPrefix}_tree.root

        # now that we have all information, get data
        script=$jobPrefix.sh

        echo export SCRAM_ARCH="slc5_amd64_gcc462" > $script
        echo export VO_CMS_SW_DIR=/cvmfs/cms.cern.ch >> $script
        echo source $VO_CMS_SW_DIR/cmsset_default.sh >> $script
        echo cd $HOME/CMSSW_5_3_8/src >> $script
        echo cmsenv >> $script
        echo cd $HOME/treeWriter >> $script
        echo make >> $script

        echo ./executable $outputFileName $files_to_submit >> $script
        chmod +x $script
        qsub -b y -j y -l h_cpu=7:00:00 -l site=hh `pwd`/$jobPrefix.sh
        # i: merge stdout and stderr
        # o: log file
    done # all jobs
    echo "rm ${job_name}.${version}__*.sh" >> $fetchScript
    echo "rm ~/${job_name}.${version}__*.sh.o*" >> $fetchScript
    echo "hadd $outputFolder/${job_name}.${version}_tree.root $outputFolder/${job_name}.${version}__*.root" >> $fetchScript
    echo "rm $outputFolder/${job_name}.${version}__*.root" >> $fetchScript
done #dataset
