#!/bin/bash

export LD_LIBRARY_PATH=/opt/d-cache/dcap/lib64:/afs/desy.de/products/root/amd64_rhel60/5.34.00/lib:/usr/lib64/perl5/5.10.0/x86_64-linux-thread-multi/CORE
export PATH=$PATH:/afs/desy.de/products/root/amd64_rhel60/5.34.00/bin/
cd $TMPDIR

# run command
#./splitTree dcap://dcache-cms-dcap.desy.de//pnfs/desy.de/cms/tier2/store/user/kiesel/nTuples/T5wg_400_V04/susyEvents_94_1_YLB.root
/afs/desy.de/user/k/kiesel/scratch/singlePhoton/SplitTree/splitTree dcap://dcache-cms-dcap.desy.de/$1

dCache=srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=

for file in *root; do
    # hadd all local and remote files with the same modulename
    modelname=$(echo $file|cut -d '_' -f1,2,3)
    fileInDCache=/pnfs/desy.de/cms/tier2/store/user/kiesel/nTuples/T5wg_V04/${modelname}.root
    echo file: $file
    echo model: $modelname
    echo fileindcache: $fileInDCache
    if [ -f $fileInDCache ]; then
        echo "Point already in dcache."
        hadd ${modelname}.root $fileInDCache ${modelname}_*.root
        srmrm ${dCache}$fileInDCache
    elif [[ $(ls ${modelname}*root|wc -w) > 1 ]]; then
        echo "Several points on woring node"
        hadd ${modelname}.root ${modelname}_*.root
    else
        echo "Only file of this point"
        mv ${modelname}_*.root ${modelname}.root
    fi
    echo "Move file to dcache."
    gfal-copy file:///`pwd`/${modelname}.root ${dCache}$fileInDCache
    echo "Delete local files"
    rm ${modelname}.root ${modelname}_*.root
done
