#!/bin/bash

export LD_LIBRARY_PATH=/opt/d-cache/dcap/lib64:/afs/desy.de/products/root/amd64_rhel60/5.34.00/lib:/usr/lib64/perl5/5.10.0/x86_64-linux-thread-multi/CORE
export PATH=$PATH:/afs/desy.de/products/root/amd64_rhel60/5.34.00/bin/
#cd $TMPDIR

# run command
/afs/desy.de/user/k/kiesel/scratch/singlePhoton/SplitTree/splitTree $1

